# -*- coding: utf-8 -*-
"""CIE1_ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOCRHjPb6_CtxRGYJc1D6_vNeHPuk_9M
"""

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('mtcars.csv')
plt.hist(df['mpg'],bins=10,edgecolor='k')
plt.title('histogram')
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('mtcars.csv')
plt.title('scatter')
plt.scatter(df['mpg'],df['wt'])
plt.show()

import pandas as pd
import numpy as np
sr1=([1,2,3,4,5])
sr2=([2,4,6,8,10])
set1=set(sr1)
set2=set(sr2)
intersection=set1.intersection(set2)
ans=list(intersection)
ans

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('mtcars.csv')
trans=(df['am'].value_counts())
trans.plot(kind='bar')
plt.xlabel('transmision')
plt.ylabel('frequency')
plt.title('frequency distribution')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('mtcars.csv')
plt.boxplot(df['mpg'])
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.show()

import pandas as pd
import numpy as np
Series_A=pd.Series([1,2,3,4,5])
Series_B=pd.Series([2,4,6,8,10])
cmn=Series_A[Series_A.isin(Series_B)]
df=np.abs(cmn)
print(df.values)